create table CustomerConnectionDown
(
    timestamp          DateTime,
    Idx                UInt32,
    Period             UInt32,
    APN                String,
    Customer           String,
    AccessType         UInt8,
    Terminal           String,
    AddrIp             String,
    Status             UInt32,
    AS                 String,
    IpSGSN             String,
    MaxTcpSession      UInt32,
    NPacket            UInt32,
    NByte              UInt64,
    NByteTcp           UInt64,
    NByteUdp           UInt64,
    ByteApp0           UInt64,
    PackApp0           UInt32,
    ByteApp1           UInt64,
    PackApp1           UInt32,
    ByteApp2           UInt64,
    PackApp2           UInt32,
    ByteApp3           UInt64,
    PackApp3           UInt32,
    ByteApp4           UInt64,
    PackApp4           UInt32,
    ByteApp5           UInt64,
    PackApp5           UInt32,
    ByteApp6           UInt64,
    PackApp6           UInt32,
    ByteApp7           UInt64,
    PackApp7           UInt32,
    ByteApp8           UInt64,
    PackApp8           UInt32,
    ByteApp9           UInt64,
    PackApp9           UInt32,
    ByteApp10          UInt64,
    PackApp10          UInt32,
    ByteApp11          UInt64,
    PackApp11          UInt32,
    ByteApp12          UInt64,
    PackApp12          UInt32,
    ByteApp13          UInt64,
    PackApp13          UInt32,
    ByteApp14          UInt64,
    PackApp14          UInt32,
    ByteApp15          UInt64,
    PackApp15          UInt32,
    ByteApp16          UInt64,
    PackApp16          UInt32,
    ByteApp17          UInt64,
    PackApp17          UInt32,
    ByteApp18          UInt64,
    PackApp18          UInt32,
    OsNum              UInt8,
    Fingerprint        String,
    Device             String,
    LocInfo            String,
    ServproviderField0 String,
    ServproviderField1 String,
    IdxCnx             UInt32,
    IdxMainCnx         UInt32,
    MaxVol10s          UInt32,
    NbSecActive        UInt32,
    Probe              String,
    Country            String,
    TypeConnection     UInt8,
    ProbeTimestamp     DateTime
)
    engine = MergeTree PARTITION BY toYYYYMM(timestamp)
        ORDER BY timestamp
        SETTINGS index_granularity = 8192;

